- src: cchurch.admin-users
  version: 0.8.5
- src: geerlingguy.firewall
  version: 2.5.0
- src: geerlingguy.swap
  version: 1.0.1
- src: manala.apt
  version: 2.0.11
- src: manala.fail2ban
  version: 2.0.1
- src: manala.motd
  version: 2.0.1
- src: manala.ntp
  version: 2.0.1
- src: manala.ssh
  version: 2.0.2
- src: manala.sudo
  version: 2.0.2
- src: manala.timezone
  version: 2.0.1
- src: manala.vim
  version: 2.0.1
- src: stouts.hostname
  version: 1.1.0
- src: ypsman.resolv

